### ISSUE TITLE
default installation fails with 'list index out of range'

### ISSUE THREAD

**Issue by Bashar** [opps/opps#316]
I followed the Run example steps at http://www.oppsproject.org/en/latest/#run-example with success output, then loading the page gives the error list index out of range

complete error as follows:

``` django
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 1.6.2
Python Version: 2.7.3
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.redirects',
 'opps.contrib.admin',
 'grappelli.dashboard',
 'grappelli',
 'django.contrib.admin',
 'opps.core',
 'opps.core.tags',
 'opps.containers',
 'opps.boxes',
 'opps.channels',
 'opps.containers',
 'opps.articles',
 'opps.archives',
 'opps.images',
 'opps.sitemaps',
 'opps.flatpages',
 'opps.archives',
 'opps.fields',
 'opps.api',
 'opps.contrib.fileupload',
 'south',
 'appconf',
 'haystack',
 'mptt',
 'googl',
 'djcelery']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
 'opps.contrib.multisite.middleware.DynamicSiteMiddleware',
 'opps.contrib.mobile.middleware.MobileDetectionMiddleware')


Traceback:
File "/home/username/Projects/django/oppsenv/local/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/core/handlers/base.py" in get_response
  90.                 response = middleware_method(request)
File "/home/username/Projects/django/opps/opps/contrib/multisite/middleware.py" in process_request
  30.         site = self.get_hosting(hosting)
File "/home/username/Projects/django/opps/opps/contrib/multisite/middleware.py" in get_hosting
  26.             return Site.objects.order_by('id')[0]
File "/home/username/Projects/django/oppsenv/local/lib/python2.7/site-packages/Django-1.6.2-py2.7.egg/django/db/models/query.py" in __getitem__
  132.         return list(qs)[0]

Exception Type: IndexError at /
Exception Value: list index out of range
```

i'm trying to run it via virtualenv on ubuntu

**Comment by intoro** [comment]
when I run:
`python manage.py migrate`
after running:
`python manage.py syncdb --noinput`
I get:
```
vagrant@vagrant:~/opps/example$ python manage.py migrate
UnknownMigration: Migration 'djcelery:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/south/migration/base.py", line 313, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/vagrant/.local/lib/python2.7/site-packages/djcelery/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```
When I run
`python manage.py runserver`
it starts but I recieve this error:
```
IndexError at /
list index out of range
```

**Comment by avelino** [comment]
Django version?

**Comment by intoro** [comment]
1.5
